name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
      - run: npm run build

    #   - name: Build Elevnty site
    #     uses: TartanLlama/actions-eleventy@v1.3
    #     with:
    #       args: --output site
    #       install_dependencies: true

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container to GHCR
        uses: docker/build-push-action@v5
        with:
            context: .
            platforms: linux/amd64
            push: true
            tags: |
                ghcr.io/ironicbadger/neat-starter:latest
          